name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v
